config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'types/search', to: 'types#search', as: :search_types
  resources :types
  get 'subtypes/search', to: 'subtypes#search', as: :search_subtypes
  resources :subtypes
  get 'items/search', to: 'items#search', as: :search_items
  resources :items do
    resources :reservations, only: [:create]
  end
  resources :reservations
  resources :inventories, only:[:new,:create]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_general_card.html.erb
  <div class="general-card mb-3">
    <div class="general-image">
      <% unless elem.image.service_url.nil?  %>
        <%= link_to child_path, {query: elem.name} do %>
          <%= cl_image_tag elem.image.key, width: 300, height: 200, crop: :fit, :class => ""%>
        <% end %>
      <% end %>
    </div>
    <div class="general-info">
      <%= link_to child_path, {query: elem.name} do %>
        <h1> <%= elem.name %></h1>
        <p><strong>Descripcion:</strong><%= elem.description %></p>
      <% end %>
      <br/>
      <% if current_user.admin? %>
        <%= button_to "Eliminar", elem_path, method: :delete, data: { confirm: "Estas seguro? si eliminas un tipo, te eliminaras todos sus subtipos, los items asociados a esos subtipos y las reservaciones que anteriormente se hayan hecho" }, class: "btn btn-danger" %>
      <% end %>
    </div>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "yllen.jpg" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

<% if user_signed_in? %>
  <div class="navbar-medium">

    
    <span><%= link_to "Tipos", types_path %></span>
    <h4>|</h4>
    <span><%= link_to "Subtipos",subtypes_path %></span>
    <h4>|</h4>
    <span><%= link_to "Items",items_path  %></span>
    <h4>|</h4>
    <span><%= link_to "home","/"  %></span>
    <% if current_user.admin? %>
      <h4>|</h4>
      <span><%= link_to "Pedidos",reservations_path  %></span>
      <h4>|</h4>
      <span><%= link_to "Inventario",new_inventory_path  %></span>
    <% end %>

  </div>
<% end %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "/", class: "nav-link" %>
        </li>

        <li class="nav-item dropdown">
          <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHn2z7r_YL3GXWi6BJzX5LwtfphQGkUpWWBA&usqp=CAU", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_pagination.html.erb
<div class="container ">
  <div class="vertical-scroll vh-80">
    <div class=<%= instance == Item ? "grid-container" : ""%>>
      <% array.each do |elem| %>
        <% if instance == Item %>
          <%= render "shared/simple_card", item: elem %>
        <% elsif instance == Type %>
          <%= render "shared/general_card", elem: elem, child_path: subtypes_path({query:elem.name}), elem_path: type_path(elem) %>
        <% elsif instance == Subtype %>
          <%= render "shared/general_card", elem: elem, child_path: items_path({query:elem.name}), elem_path: subtype_path(elem) %>
        <% elsif instance == Reservation %>
          <%= render "shared/reservation_card", elem: elem, instance: instance, elem_path: reservation_path(elem) %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="container d-flex justify-content-center my-4">
    <%= paginate array%>
  </div>
</div>

app/views/shared/_reservation_card.html.erb
<div class="general-card mb-3">
  <div class="general-image">
    <%= cl_image_tag elem.item.images.first.key, width: 300, height: 200, crop: :fit, :class => ""%>
  </div>
  <div class="general-info">
    <div class="row">
      <div class="col">
        <h1> <%= elem.item.name %></h1>
        <p><strong>Usuario:</strong><%= elem.user.full_name %></p>
        <p><strong>Cantidad:</strong><%= elem.quantity %></p>
        <%= link_to "ir al objeto", item_path(elem.item),:class => "btn btn-primary my-2"%>
      </div>
      <div class="col pt-5">
        <p><strong>telefono:</strong><%= elem.user.phone_number %></p>
        <p><strong>correo:</strong><%= elem.user.email %></p>
        <%= simple_form_for elem do |f| %>
          <div class="form-inline">
            <div class="inline-item">
              <%= f.input :enabled,:label =>"Visible", :class => "my-0" %>
              <%= f.input :answered,:label =>"Contestado", :class => "my-0"%>
            </div>
          </div>
          <%= f.submit "Submit", class: "btn btn-primary" %>
        <% end %>
      </div>

    </div>


  </div>
</div>

app/views/shared/_search_bar.html.erb
<%= form_tag path, method: :get, class: "row my-3" do %>
  <div class="col-8">
    <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Busca por tipo, subtipo o item"
    %>
  </div>
  <div class="col-1">
    <%= submit_tag "Buscar", class: "btn btn-primary" %>
  </div>
  <% if current_user.admin? && path[1..-1] != "reservations"%>
    <div class="col-3 ">
    <div class="filtro " ><h6><%=link_to "crear nuevo #{path[1..-2]}", "#{path}/new",class:"btn btn-primary" %></h6></div>
  </div>
  <% end %>
<% end %>

app/views/shared/_simple_card.html.erb
<%= link_to item_path(item) do  %>
  <div class="small-catch-card">

    <div class="card-side front">

      <div class="upper-container d-flex justify-content-center align-items-center">
        <h2 ><%= item.name %></h2>
      </div>
      <div class="catch-pic d-flex align-items-center justify-content-center">
        <%= cl_image_tag item.images.first.key %>

      </div>

    </div>

    <div class="card-side back ">
      <div class="head d-flex flex-column">
        <h2 class="align-self-center">Detalles</h2>
      </div>
      <ul class="vertical-scroll">
        <li><strong>precio: </strong><%= item.price %></li>
        <li><strong>stock: </strong><%= item.quantity %></li>
        <li><strong>tipo: </strong><%= item.subtype.type.name %></li>
        <li><strong>subtipo: </strong><%= item.subtype.name %></li>
      </ul>
      <hr>
      <div class="content vertical-scroll">
        <h5><strong> Description</strong></h5>
        <p><%= item.description %></p>
      </div>
    </div>

  </div>
<% end %>